################################
# Window
################################
[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 10, y = 10 }
dynamic_padding = false
opacity = 1.0
decorations = "full"

################################
# Font
################################

[font]
size = 17.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

################################
# Cursor
################################
[cursor]
style = "Block"
blink_interval = 0

################################
# Shell
################################
[terminal.shell]
program = "/usr/bin/zsh"

################################
# Selection
################################
[selection]
save_to_clipboard = true

################################
# Colors
################################
[colors.primary]
foreground = "#979eab"
background = "#282c34"

[colors.cursor]
cursor = "#cccccc"
text = "#282c34"

[colors.selection]
foreground = "#282c34"
background = "#979eab"

[colors.normal]
black   = "#282c34" # color0
red     = "#e06c75" # color1
green   = "#98c379" # color2
yellow  = "#e5c07b" # color3
blue    = "#61afef" # color4
magenta = "#be5046" # color5
cyan    = "#56b6c2" # color6
white   = "#979eab" # color7

[colors.bright]
black   = "#393e48" # color8
red     = "#d19a66" # color9
green   = "#56b6c2" # color10
yellow  = "#e5c07b" # color11
blue    = "#61afef" # color12
magenta = "#be5046" # color13
cyan    = "#56b6c2" # color14
white   = "#abb2bf" # color15

[terminal]

