$CITY = Bojonegoro
$COUNTRY = ID

background {
    monitor = 
    path = screenshot
    blur_passes = 3
    contrast = .8916
    brightness = .8172
    vibrancy = .1696
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
}

input-field {
    size = 230, 45

    outline_thickness = 1
    dots_size = .2
    dots_spacing = .2
    dots_center = true
    outer_color = rgba(232, 234, 237, .4)
    inner_color = rgba(100, 114, 125, .4)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    font_family = SF Pro Text Semibold
    placeholder_text = Enter Password
    font_color = rgba(255, 255, 255, 0.6)
    hide_input = false
    position = 0, -300
    halign = center
    valign = center
}

# Time
label {
    monitor = 
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgba(216, 222, 223, .7)
    font_size = 85
    font_family = SF Pro Display Bold
    position = 0, 310
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(255, 255, 255, 1)
    font_size = 30
    font_family = SF Pro Display Semibold
    position = 0, 400
    halign = center
    valign = center
}
# Profile-Photo
image {
    monitor = 
    path = /home/axel/.config/hypr/hyprlock/profile-picture.png
    border_color = rgba(255, 255, 255, .7)
    border_size = 1
    size = 150
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd = 
    position = 0, 0
    halign = center
    valign = center
}

# USER
label {
    monitor = 
    text = $USER
    color = rgba(216, 222, 233, 0.7)
    font_size = 20
    font_family = SF Pro Text Semibold
    position = 0, -120
    halign = center
    valign = center
}

# CURRENT SONG (Spotify)
label {
    monitor = 
    text = cmd[update:1000] echo "$(~/.config/hypr/hyprlock/scripts/spotify-playing.sh)"
    color = rgba(255, 255, 255, .7)
    font_size = 18
    font_family = SF Pro Display Semibold
    position = 100, 0
    halign = left
    valign = center
}

# WEATHERCAST & LOCATION
label {
    monitor = 
    text = cmd[update:1000] echo "$(bash ~/.config/hypr/hyprlock/scripts/weather.sh)"
    shadow_passes = 1
    shadow_boost = .5
    color = rgba(255, 255, 255 , .7)
    font_size = 18
    font_family = SF Pro Display Semibold

    position = 95.5, -40
    halign = left
    valign = center
}
